spring:
  redis:
    host: 127.0.0.1
    #2.0+不在采用JRedis(直连redis-server, 非线程安全)
    #lettuce基于Netty, 线程安全
    lettuce:
      pool:
        max-active: 20 #负值表示没有限制
        max-idle: 10
        min-idle: 5
    port: 6379
    #连接密码
    timeout: 10000
    #默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    password:
