eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8764/eureka/
    instance:
        hostname: eureka1
server:
    port: 8763
spring:
    application:
        name: eureka-server1
