eureka:
    client:
        serviceUrl:
            #设置服务注册中心地址，指向另一个注册中心(集群注册)
            defaultZone: http://localhost:8763/eureka/,http://localhost:8764/eureka/
server:
    port: 8765
spring:
    application:
        name: eureka-provider
