eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 250
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 1000
server:
  port: 5555
spring:
  application:
    name: api-gateway

zuul:
  retryable: true
  routes:
    hello-service:
      retryable: false
      ## 面向服务的路由
      service-id: hello-service
      path: /hello-service/**
      feign-consumer: /feign-consumer/**
      ## 传统路由单实例配置
#      path: /hello-service/**
#      url: http://localhost:8081/
