eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8763/eureka/,http://localhost:8764/eureka/
server:
    port: 8766
spring:
    application:
        name: eureka-consumer
