// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xujian.proto

package com.xujian.netty.grpc;

public interface XujianRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xujian.netty.grpc.XujianRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   */
  String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 2;</code>
   */
  String getLastName();
  /**
   * <code>string lastName = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
