// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addphone.proto

package com.xujian.netty.addphone;

public interface AddPhoneToUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:addphone.AddPhoneToUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool result = 1;</code>
   */
  boolean getResult();
}
