mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.xujian.mapper
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/xujian
    username: root
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
