// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xujian.proto

package com.xujian.netty.grpc;

public interface XujianResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xujian.netty.grpc.XujianResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   */
  String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
