server:
  port: 9091
spring:
  application:
    name: sleuth-zipkin-client1
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
#      rate: