spring:
  application:
    name: spring-cloud-feign
#eureka:
#  client:
#    server-url:
#      defaultZone: http://localhost:8761/eureka/

feign:
  baseUrl: http://localhost:8080
  hystrix:
    shareSecurityContext: true    # 设置这个值会自动配置一个Hystrix并发策略会把securityContext从主线程传输到你使用的Hystrix command
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMillisecond: 10000   # hystrix超时时间调整 默认为1s
        circuitBreaker:
          sleepWindowInMilliseconds: 10000     # 短路多久以后开始尝试是否恢复，默认5s
          forceClosed: false # 是否允许熔断器忽略错误,默认false, 不开启
    enabled: true
#  compression:
#    request:
#      enable: true  #配置请求支持GZIP压缩，默认为false
#      mime-types: text/xml, application/xml, application/json  #配置压缩支持的Mime Type
#      min-request-size: 2048 #配置压缩数据大小的上下限
#    reponse:
#      enable: true #配置响应支持GZIP压缩，默认为false
#  httpclient:
#    enable: false
#  okhttp:
#    enable: true
#  client:
#    config:
#      ##对名字为 github-client 的feign client做配置
#      github-client:                                # 对应GitHubApiClient类的@FeignClient的name属性值
#        decoder404: false                           # 是否解码404
#        loggerLevel: full                           # 日志记录级别
turbine:
  aggregator:
    cluster-config: default     #需要监控的服务集群名
  app-config: consul-client    #需要监控的服务名
  cluster-name-expression: new String('default')
  #  instanceUrlSuffix:
  #      default: actuator/hystrix.stream    #key是clusterConfig集群的名字，value是hystrix监控的后缀，springboot2.0为actuator/hystrix.stream

  ## 全局连接超时时间
ribbon:
  ConnectTimeout: 250
  ## 全局接口调用超时时间
  ReadTimeout: 10000
  ## 全局重试所有请求（POST 请求等）开关
  OkToRetryOnAllOperations: false

  ## 针对 hello-service 服务，重试切换的实例数
hello-service:
    ribbon:
      MaxAutoRetriesNextServer: 1
      ## 针对 hello-service 服务，对当前实例重试次数
      MaxAutoRetries: 0