eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8763/eureka/
    instance:
        hostname: eureka2
server:
    port: 8764
spring:
    application:
        name: eureka-server2
