server:
  port: 8888

spring:
  application:
    name: springcloud-server
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:8888
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: xujian
    password: 123456

info:
  name: server
  description: @project.description@
  version: @project.version@

#?????Actuator Endpoints???endpoints
management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,env,mappings,metrics,trace,sessions,threaddump
        exclude:
    jmx: #Java Management Extensions??Java????
      exposure:
        include: health,info,env
        exclude: